import localFont from "next/font/local";
import "./globals.css";
import NextTopLoader from "nextjs-toploader";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
<<<<<<< HEAD
  title: "CP Club",
  description: "Generated by create next app",
=======
  title: "CP Club 2024",
  description: "Developed by COC",
>>>>>>> 815aba018d4f024a7d13c0659c4f218693668c77
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextTopLoader />
        {children}
      </body>
    </html>
  );
}
